### PR TITLE
Code needing documentation

### PR DESCRIPTION
**Pull request by nguyenj21**
This code needs better documentation Issue #93.

### CODE REVIEW

**Review by salazw1 — APPROVED** [review]
clear and concise documentation, well done!

**Review by junxjr — APPROVED** [review]
Great documentation.

**Comment by nguyenj21** [comment]
Fixed issue #93 by adding better documentation
https://chat.openai.com/share/c148dafe-6660-44e3-8fc6-f1bfb3e7e03d

**Review by jusasin — APPROVED** [review]
I would agree, this needs better documentation.

**Pull request merged**
